import { createHash } from 'node:crypto';

const HASH_LINE = /^<!-- arcana:hash:sha256 ([0-9a-f]{64}) -->$/;

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function generatorNotice(version: string): string {
  return `<!-- generated by arcana v${version} from deck.yaml — edit deck.yaml, not this file -->`;
}

/** Append the tamper-evident hash line. Content must end with a newline. */
export function stamp(content: string): string {
  const body = content.endsWith('\n') ? content : `${content}\n`;
  return `${body}<!-- arcana:hash:sha256 ${sha256(body)} -->\n`;
}

export type StampStatus = 'ok' | 'missing' | 'mismatch';

/** Split a stamped file into its body and hash line; undefined if unstamped. */
function splitStamp(fileText: string): { body: string; hash: string } | undefined {
  const withoutTrailing = fileText.endsWith('\n') ? fileText.slice(0, -1) : fileText;
  const lastBreak = withoutTrailing.lastIndexOf('\n');
  const lastLine = withoutTrailing.slice(lastBreak + 1);
  const match = HASH_LINE.exec(lastLine);
  if (!match) return undefined;
  return { body: withoutTrailing.slice(0, lastBreak + 1), hash: match[1]! };
}

export function isStamped(fileText: string): boolean {
  return splitStamp(fileText) !== undefined;
}

export function verifyStamp(fileText: string): StampStatus {
  const parts = splitStamp(fileText);
  if (!parts) return 'missing';
  return sha256(parts.body) === parts.hash ? 'ok' : 'mismatch';
}

/** Remove the hash line and any arcana generator notices (used by eject). */
export function stripStamp(fileText: string): string {
  const parts = splitStamp(fileText);
  const body = parts ? parts.body : fileText;
  return body
    .split('\n')
    .filter((line) => !/^<!-- generated by arcana v.* -->$/.test(line))
    .join('\n')
    .replace(/^\n+/, '');
}
